import torch
import time

print("\n========================================================")
print(" PHYSICAL AI DYNAMICS: CONTACT DYNAMICS & FRICTION (DAY 16) ")
print("========================================================\n")

def check_for_slip(Fz, Fx, mu=0.6):
    """
    The Friction Solver (Vectorized for 1,000,000 robots).
    
    In a physics engine, if a foot pushes sideways (Fx) harder than the 
    downward force (Fz) multiplied by the friction coefficient (mu), 
    the foot slips.
    
    Args:
        Fz (Tensor): Normal force pushing down into the floor (Shape: N, 1)
        Fx (Tensor): Tangential force pushing sideways (Shape: N, 1)
        mu (float): The coefficient of friction (e.g. 0.6 for mud/dirt)
        
    Returns:
        slip_mask (Tensor): A boolean mask where True = robot slipped.
        penalties (Tensor): Reward penalties to apply to the policy.
        
    Note (Energy Leakage): 
    If we don't resolve these forces correctly using constraints, the physics engine
    can suffer from 'Energy Leakage', causing the robot to vibrate and eventually explode.
    """
    # 1. The Coulomb Friction Cone Limit
    # How much horizontal force can the ground support before breaking traction?
    max_grip_force = mu * Fz
    
    # 2. Check if the robot's sideways force exceeds the grip limit
    # We use torch.abs(Fx) because slipping can happen left or right
    slip_mask = torch.abs(Fx) > max_grip_force
    
    # 3. Apply the Mercenary Penalty
    # -10 points for slipping. 0 points for gripping successfully.
    # This forces the Neural Network (PPO) to learn stable walking dynamics
    # instead of just thrashing its legs around.
    penalties = torch.zeros_like(Fx)
    penalties[slip_mask] = -10.0
    
    return slip_mask, penalties

# --- THE NVIDIA RTX 4090 BENCHMARK ---
num_robots = 1_000_000

print(f"[+] Booting up {num_robots:,} Contact Constraints...")

# Simulate 1,000,000 robot feet hitting the ground.
# Normal force (Fz) is mostly robot weight (e.g. ~100 to 200 Newtons)
Fz = torch.empty(num_robots, 1).uniform_(100.0, 200.0)

# Simulate the lateral force (Fx) generated by the robot trying to walk
# Some robots will step smoothly (low Fx), some will try to sprint (high Fx)
Fx = torch.empty(num_robots, 1).uniform_(-150.0, 150.0)

# Muddy coffee farm soil coefficient
friction_coefficient = 0.6

print(f"[!] Solving the Coulomb Friction Cone for all agents in parallel...")
start_time = time.time()

slip_mask, penalties = check_for_slip(Fz, Fx, mu=friction_coefficient)

end_time = time.time()

# --- RESULTS ---
benchmark_ms = (end_time - start_time) * 1000
total_slipped = slip_mask.sum().item()
percentage_slipped = (total_slipped / num_robots) * 100

print("========================================================")
print(f" SUCCESS: Resolved 1,000,000 contact manifolds in {benchmark_ms:.3f} ms.")
print(f"\n Friction Diagnostics (mu = {friction_coefficient}):")
print(f"  Total Slipped Agents: {total_slipped:,} ({percentage_slipped:.1f}%)")
print(f"  Total Penalties Assigned: {penalties.sum().item():,.0f} points")

print(f"\n Example Robot [0] Dynamics:")
print(f"  Downward Force (Fz): {Fz[0].item():.2f} N")
print(f"  Max Grip Possible:   {(Fz[0] * friction_coefficient).item():.2f} N")
print(f"  Sideways Force (Fx): {Fx[0].item():.2f} N")
print(f"  Result:              {'SLIPPED (Penalty -10)' if slip_mask[0].item() else 'GRIP HELD (No Penalty)'}")
print("========================================================\n")

# --- THE C++ CHALLENGE (Mental Note for A2SV) ---
# In Python/PyTorch, we do this matrix calculation in ~2ms on GPU.
# In C++ for A2SV, you will have to manually manage the memory for 1D line intersections.
# Understanding the pure math here makes writing the low-level C++ drastically easier.
