from pxr import Usd, UsdGeom
import os

print("\n========================================================")
print(" PHYSICAL AI DYNAMICS: OPENUSD ARCHITECTURE (DAY 5) ")
print("========================================================\n")

# 1. CREATE THE STAGE (The Reality Container)
file_path = "robot_architecture.usda"
print(f"[+] Creating new USD Stage at: {file_path}...")

# Create a new USD file in memory
stage = Usd.Stage.CreateNew(file_path)

# Set the "Up" axis to Z (Standard for Robotics/Isaac Lab)
UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)

# 2. ARCHITECT THE HIERARCHY TREE
print("[+] Building the Robot Prim Tree...")

# Create the Root World Prim
world_prim = UsdGeom.Xform.Define(stage, '/World')
stage.SetDefaultPrim(world_prim.GetPrim())

# Create the Environment Prim inside World
env_prim = UsdGeom.Xform.Define(stage, '/World/Environment')

# Create the Robot Root Prim inside World
robot_prim = UsdGeom.Xform.Define(stage, '/World/Robot')

# Add a Base Mesh to the Robot (A simple sphere for now)
base_mesh = UsdGeom.Sphere.Define(stage, '/World/Robot/BaseLink')
base_mesh.GetRadiusAttr().Set(2.0)

# Add an Arm Link to the Robot (A simple cylinder)
arm_mesh = UsdGeom.Cylinder.Define(stage, '/World/Robot/ArmLink')
arm_mesh.GetHeightAttr().Set(5.0)

# 3. SAVE THE FILE TO DISK
print("[!] Saving .usda file to disk...\n")
stage.GetRootLayer().Save()

# 4. PRINT THE RESULTS
print("========================================================")
print(" SUCCESS: USD Hierarchy Built.")
print("========================================================")
print("Here is the raw USD Code generated by Python:")
print("--------------------------------------------------------")

# Open the text file and print it so you can see the "HTML of 3D"
with open(file_path, 'r') as f:
    print(f.read())

print("--------------------------------------------------------\n")

# Clean up the file so we can run the script multiple times without error
os.remove(file_path)
